s_x = int(input("Задайте рабочую площадь\n"'Введите координаты по х\n'))
s_y = int(input('Введите координаты по Y\n'))
v_1 = int(input('Введите с какой V движется первый человек (в м/с)\n'))
v_2 = int(input('Введите с какой V движется второй человек (в м/с)\n'))
s = int(input("Введите расстояние между 1 и 2 человеком (в метрах)\n"))
t = s /(v_1+v_2)
s_1 = int(t * v_1)
R= 5
import tkinter
my_window=tkinter.Tk()
my_window.title('Задачи')
v0_label=tkinter.Label(text=f'Cкорость первого {v_1,}'f'Точка пересечения {s_1}')
v1_label=tkinter.Label(text=f'Cкорость второго {v_2}')
s_label=tkinter.Label(text=f'Общее расстояние {s}')
my_canva=tkinter.Canvas(my_window,width=s_x,height=s_y,background='white')
v0_label.pack()
v1_label.pack()
s_label.pack()
my_canva.create_line(0,(s_y/2),s_1,(s_y/2),fill='blue',width=5)
my_canva.create_line(s_1,(s_y/2),s,(s_y/2),fill='red',width=5)
my_canva.create_text(s_1,(s_y/2-25),text='точка пересечения')
my_canva.create_oval(s_1-R,(s_y/2)-R,s_1+R,(s_y/2)+R,fill='orange')
my_canva.pack()
my_window.mainloop()